#!/bin/bash

outputfile="${1%.*}".png

npx mmdc --scale 4 -i $1 -o $outputfile
convert -trim $outputfile $outputfile
width=$(identify -format "%[fx:w]" $outputfile)
height=$(identify -format "%[fx:h]" $outputfile)

convert -gravity center -extent $(($width+50))x$(($height+50)) $outputfile $outputfile
